function [this,v,w]=init(this,H)

[v,w]=init(H);

this.options=gaoptimset(this.options,'PopulationType','bitstring',...
    'Generations',1,...
    'StallTimeLimit',90,...
    'MigrationInterval',Inf,...
    'CrossoverFraction',0.5,...
    'CrossoverFcn',@crossovertwopoint,...
    'SelectionFcn',@selectionroulette,...
    'MutationFcn',{@mutationuniform,0.02});
  
end
